name: Run OpenMeteo API

on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run script and capture output
              id: run_script
              run: |
                  python scraper_test.py > script_output.txt
                  cat script_output.txt  # Display the output in the logs

            # Create a timestamped file name and save output
            - name: Save output with date-time filename
              run: |
                  timestamp=$(date +"%Y%m%d_%H%M%S")
                  filename="scraper_output_$timestamp.txt"
                  mv script_output.txt "$filename"
                  echo "Saved output to $filename"

            # Commit the new file to the repository
            - name: Commit changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add scraper_output_*.txt
                  git commit -m "Add scraper output with date-time"
                  git push
